/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.lawelyan.xbmccontroller.gui;

import de.lawelyan.xbmccontroller.Main;
import de.lawelyan.xbmccontroller.xbmcconnector.Movie;
import de.lawelyan.xbmccontroller.xbmcconnector.MovieList;
import de.lawelyan.xbmccontroller.xbmcconnector.models.MovieModel;
import java.awt.Point;
import java.awt.Rectangle;

import java.awt.Toolkit;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Rainer
 */
public class WinTest extends javax.swing.JFrame {

    private static WinTest mainWindow;

    public void refresh() {
        try {
            infoArea.setText("hier war mal ein xbmcconnect aufruf....");
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * Zeigt das Hauptfenster
     */
    public static void load() {
        mainWindow.toFront();
        mainWindow.setVisible(true);
    }

    /**
     * Schliesst das Hauptfenster (es bleibt bestehen und kann wiederhergestellt
     * werden)
     */
    public static void close() {
        mainWindow.dispose();
    }

    /**
     * Creates new form WinTest
     */
    private WinTest() {
        initComponents();

        setTitle("XBMC Controller - for a better XBMC");
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        setSize(1400, 600);
        setIconImage(new ImageIcon(Toolkit.getDefaultToolkit().getImage(GuiConfig.ICON_ONLINE)).getImage());
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLoadMovies = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoArea = new javax.swing.JTextArea();
        jButtonLoadMovieById = new javax.swing.JButton();
        movieId = new javax.swing.JTextField();
        jButtonQuit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonLoadMovies.setText("Lade Filmliste");
        jButtonLoadMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadMoviesActionPerformed(evt);
            }
        });

        infoArea.setColumns(20);
        infoArea.setRows(5);
        infoArea.setText("lade Informationen....");
        jScrollPane2.setViewportView(infoArea);

        jButtonLoadMovieById.setText("Lade Film ID");
        jButtonLoadMovieById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadMovieByIdActionPerformed(evt);
            }
        });

        movieId.setText("1");
        movieId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieIdActionPerformed(evt);
            }
        });

        jButtonQuit.setText("Quit");
        jButtonQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLoadMovies)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonLoadMovieById)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movieId, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonQuit))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonQuit)
                .addGap(23, 23, 23)
                .addComponent(jButtonLoadMovies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonLoadMovieById)
                    .addComponent(movieId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoadMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadMoviesActionPerformed
        try {
            new Thread(new MovieList() {
                @Override
                public void callback() {
                    infoArea.append("\n----------------new Input----------------\n" + limits.toString() + "-------------------\n");

                    String mov = "";
                    Iterator<MovieModel> m = movies.iterator();
                    while (m.hasNext()) {
                        infoArea.append(m.next().toString());
                    }
                    infoArea.scrollRectToVisible(new Rectangle(new Point(-1, 100000000)));
                }
            }).start();

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButtonLoadMoviesActionPerformed

    private void jButtonLoadMovieByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadMovieByIdActionPerformed
        // TODO add your handling code here:
        try {
            new Thread(new Movie(movieId.getText()) {
                @Override
                public void callback() {
                    infoArea.append("\n----------------new Input----------------\n");
                    infoArea.append(movie.toString());

                }
            }).start();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButtonLoadMovieByIdActionPerformed

    private void movieIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movieIdActionPerformed

    private void jButtonQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitActionPerformed
        Main.quit();
    }//GEN-LAST:event_jButtonQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mainWindow = new WinTest();
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea infoArea;
    private javax.swing.JButton jButtonLoadMovieById;
    private javax.swing.JButton jButtonLoadMovies;
    private javax.swing.JButton jButtonQuit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField movieId;
    // End of variables declaration//GEN-END:variables
}
